# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.biswas.com:
    extends:
      file:   docker-compose-base.yaml
      service: orderer.biswas.com
    container_name: orderer.biswas.com
    networks:
      - byfn

  peer0.grower.biswas.com:
    container_name: peer0.grower.biswas.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.grower.biswas.com
    networks:
      - byfn

  peer1.grower.biswas.com:
    container_name: peer1.grower.biswas.com
    extends:
      file:  docker-compose-base.yaml
      service: peer1.grower.biswas.com
    networks:
      - byfn

  peer0.producer.biswas.com:
    container_name: peer0.producer.biswas.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.producer.biswas.com
    networks:
      - byfn

  peer1.producer.biswas.com:
    container_name: peer1.producer.biswas.com
    extends:
      file:  docker-compose-base.yaml
      service: peer1.producer.biswas.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.grower.biswas.com:7051
      - CORE_PEER_LOCALMSPID=GrowerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/grower.biswas.com/peers/peer0.grower.biswas.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/grower.biswas.com/peers/peer0.grower.biswas.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/grower.biswas.com/peers/peer0.grower.biswas.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/grower.biswas.com/users/Admin@grower.biswas.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY} ${LANG}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../artifacts/certs:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        # - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../artifacts/channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.biswas.com
      - peer0.grower.biswas.com
      - peer1.grower.biswas.com
      - peer0.producer.biswas.com
      - peer1.producer.biswas.com
    networks:
      - byfn
