version: '2'

services:
  peer0:
    container_name: peer0.grower.biswas.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.grower.biswas.com
      - CORE_PEER_ADDRESS=peer0.grower.biswas.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.grower.biswas.com:7051
      - CORE_PEER_LOCALMSPID=GrowerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/grower.biswas.com/peers/peer0.grower.biswas.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
      - 7053:7053

  peer1:
    container_name: peer1.grower.biswas.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.grower.biswas.com
      - CORE_PEER_ADDRESS=peer1.grower.biswas.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.grower.biswas.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.grower.biswas.com:7051
      - CORE_PEER_LOCALMSPID=GrowerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/grower.biswas.com/peers/peer1.grower.biswas.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 8051:7051
      - 8053:7053

  ca:
    container_name: ca.grower.biswas.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-grower
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca.grower.biswas.com-cert.pem --ca.keyfile /etc/hyperledger/28b5665c29645f5ff63627fef9eb2af32655870938749efbcb2e96fe2862300d_sk -b admin:adminpw -d'
    volumes:
      - ../artifacts/certs/peerOrganizations/grower.biswas.com/ca:/etc/hyperledger
