version: '2'

services:
  ca:
    container_name: ca.producer.biswas.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-producer
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca.producer.biswas.com-cert.pem --ca.keyfile /etc/hyperledger/0bd35d30f74a01eb396d293ad96d5b68baa7f2df453f4c05d055696a015c682b_sk -b admin:adminpw -d'
    volumes:
      - ../artifacts/certs/peerOrganizations/producer.biswas.com/ca:/etc/hyperledger


  peer0-db:
    container_name: peer0-db.producer.biswas.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=producerpeer0admin
      - COUCHDB_PASSWORD=pass

  peer1-db:
    container_name: peer1-db.producer.biswas.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=producerpeer1admin
      - COUCHDB_PASSWORD=pass


  peer0:
    container_name: peer0.producer.biswas.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.biswas.com
      - CORE_PEER_ADDRESS=peer0.producer.biswas.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.biswas.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.biswas.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-db.producer.biswas.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=producerpeer0admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/producer.biswas.com/peers/peer0.producer.biswas.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:7051
      - 9053:7053

  peer1:
    container_name: peer1.producer.biswas.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.producer.biswas.com
      - CORE_PEER_ADDRESS=peer1.producer.biswas.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.producer.biswas.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.producer.biswas.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-db.producer.biswas.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=producerpeer1admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/producer.biswas.com/peers/peer1.producer.biswas.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 10051:7051
      - 10053:7053
